# Edit your preferences below 
title: Natalia Frumkin (Natasha)
subtitle: PhD Student at UT Austin
# description: >- # this means to ignore newlines until "baseurl:"


url: "https://nfrumkin.github.io/" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "/" # the subpath of your site, e.g. /blog

urls:
    # - text: Blog
    #   url: /blog
    - text: Home
      url: /
    - text: About Me
      url : /about
    - text: Publications
      url: /pubs

# Edit these details 

author_logo: profile.png
author: Natalia Frumkin
author_bio: I am a PhD student at the Univeristy of Texas at Austin studying efficient deep learning.
author_email: "[first initial][last name]>@utexas.edu"
author_location: Austin, TX
author_website_url: "http://nfrumkin.github.io"

author_work_experiences: 
            - company_name: Arm Ltd.
              company_logo: arm.png
              company_url: https://arm.com
              designation: Research Intern
              visibility: True
            - company_name: Advanced Micro Devices
              company_logo: amd.png
              company_url: https://amd.com
              designation: Research Intern
              visibility: True
            - company_name: Los Alamos National Labratory
              company_logo: lanl.png
              company_url: https://lanl.gov
              designation: Supercomputing Intern
              visibility: True
            - company_name: Red Hat
              company_logo: redhat.png
              company_url: https://redhat.com
              designation: AI/Data Science Intern
              description: conducted research on time series anomaly detection
              visibility: true
            - company_name: Visual Information Processing Lab (BU)
              company_logo: vip.jpg
              company_url: http://vip.bu.edu/projects/vsns/privacy-smartroom/active-illumination/
              designation: Undergraduate Researcher
              description: developed an illumination testbed for light transfer analysis
              visibility: false


author_education_details:
              - college_logo: utexas.png
                college_degree: The University of Texas at Austin
                college_url: https://enyac.org/
                college_name: Electrical & Computer Engineering
                description: PhD
                visibility: true
              - college_logo: bu.png
                college_degree: Boston University
                college_name: Computer Engineering
                description: Bachelor of Science
                college_url: https://vip.bu.edu/
                visibility: true

# author_project_details:
#               - project_thumbnail: hpc.png
#                 project_title: BU High Performance Computing
#                 project_description: A club for hardware and software optimizations
#                 project_url: https://buhpc.com
#                 visibility: true

# social links
twitter_username: iCountFromZero
github_username:  nfrumkin
linkedin_username: nfrumkin

#for comments using disqus
disqus_shortname: nfrumkin

# wakatime username (coding activity)
# wakatime_username: sujaykundu777

# formspree (contact form)
formspree_email: natasha.frumkin@gmail.com

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# google analytics
google_analytics: UA-46783401-10 

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: false

# dont touch this unless required
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-algolia
# - jekyll-archives

# algolia search 
algolia:
  application_id: D9WA1YKTRQ
  index_name: blog_posts # You can replace that with whatever name you want
  files_to_exclude: []
  nodes_to_index: 'article'
  search_only_api_key: 58ffdd7cd6c45ec1577a7fcd789b1b9a

# pagination of posts
paginate: 8
per_page: 4
paginate_path: "/blog/page/:num/"

# minify 
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/