remote_theme: sujaykundu777/devlopr-jekyll  # Don't touch ( required for this theme)

# Edit your preferences below 
title: Natalia Frumkin (Natasha)
subtitle: HPC & ML Enthusiast
description: >- # this means to ignore newlines until "baseurl:"
  Natasha is a computer engineer who is passionate about learning new skills and teaching them.

url: "http://localhost:4000" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: Blog
      url: /blog
    - text: About Me
      url: /about
    - text: Contact Me
      url : /contact
    - text: Sample Page
      url: /sample-page

# Edit these details 

author_logo: profile.png
author: Natalia Frumkin
author_bio: Hi, I love cycling, learning about physics phenomena, and writing efficient code.  
author_email: "nfrumkin@bu.edu"
author_location: Boston, MA
author_website_url: "http://nfrumkin.github.io"

author_work_experiences: 
            - company_name: Red Hat
              company_logo: redhat.png
              company_url: https://redhat.com
              designation: AI/Data Science Intern
              description: researched on time series anomaly detection
              visibility: true
            - company_name: Visual Information Processing Lab (BU)
              company_logo: vip.jpg
              company_url: http://vip.bu.edu/
              designation: Undergraduate Researcher
              description: testbed developer and data collector
              visibility: true

author_education_details:
              - college_logo: bu.png
                college_name: Boston University
                college_url: bu.edu
                college_degree: Computer Engineering
                description: Bachelor of Science
                visibility: true

author_project_details:
              - project_thumbnail: hpc.png
                project_title: BU High Performance Computing
                project_description: A club for hardware and software optimizations
                project_url: https://buhpc.com
                visibility: true

# social links
twitter_username: iCountFromZero
github_username:  nfrumkin
linkedin_username: nfrumkin

#for comments using disqus
disqus_shortname: nfrumkin

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# google analytics
google_analytics: UA-46783401-10 

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# dont touch this unless required
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-remote-theme
  # - jekyll-archives

# pagination of posts
paginate: 8
per_page: 4
paginate_path: "/blog/page/:num/"

# minify 
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'


